"""baseline: progress, comprehension_record, comprehend_usage

The schema as it stood when Alembic was adopted, not a change to it.

Every deployment that predates this revision already has these three tables --
built by `Base.metadata.create_all`, which Alembic replaces -- so it is marked
as applied there with `alembic stamp head` rather than run. Running it would
fail on tables that already exist, and `progress` holds reading progress that
would hurt to lose.

Generated by autogenerate against an empty database and read against the
deployed one before landing: same columns, same nullability, same primary keys,
no missing index. That comparison is what makes stamping honest.

Revision ID: 4085885413a9
Revises: 
Create Date: 2026-08-07 12:37:01.113784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4085885413a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('comprehend_usage',
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('usage_date')
    )
    op.create_table('comprehension_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('translated_text', sa.String(), nullable=False),
    sa.Column('cloud_translation', sa.String(), nullable=True),
    sa.Column('grammar_notes', sa.String(), nullable=True),
    sa.Column('context_notes', sa.String(), nullable=True),
    sa.Column('tone_register', sa.String(), nullable=True),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('comic_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('use_stronger_model', sa.Boolean(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('comic_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('comic_id', 'chapter_id')
    )


def downgrade() -> None:
    op.drop_table('progress')
    op.drop_table('comprehension_record')
    op.drop_table('comprehend_usage')
